
name: artifact_job
on: push
jobs:
  artifact_job_one:
    name: artifact_job_one
    runs-on: ubuntu-latest
    steps:
      - name: checking_out
        uses: actions/checkout@v4
        run: echo "checkout done"
      - name: saving artifact
        uses: actions/upload-artifact@v4
        with:
          name: first_artifact
          path: ./artifacts  
      - name: endofjob
        run: echo "end of the task"
